title: Corner of the Hyper-plane
author: Robert Fekete
github_username: robert-fekete

permalink: /:categories/:year/:month/:day/:title/
show_excerpts: true

markdown: kramdown
sass:
  style: compressed

github_handle: robert-fekete
twitter_handle: "rofekete"
bitbucket_handle: robert-fekete